wandb_version: 1

activationFunc:
  value: tanh
batchSize:
  value: 164
hiddenLayer_Size:
  value: 64
learningRate:
  value: 0.0001
num_epochs:
  value: 10
num_hiddenLayers:
  value: 4
optimizer:
  value: nesterov
weightDecay:
  value: 0
weightInit:
  value: xavier
