wandb_version: 1

activationFunc:
  value: tanh
batchSize:
  value: 32
hiddenLayer_Size:
  value: 64
learningRate:
  value: 0.001
num_epochs:
  value: 5
num_hiddenLayers:
  value: 5
optimizer:
  value: nadam
weightDecay:
  value: 0
weightInit:
  value: random
