wandb_version: 1

activationFunc:
  value: relu
batchSize:
  value: 32
hiddenLayer_Size:
  value: 128
learningRate:
  value: 0.001
num_epochs:
  value: 10
num_hiddenLayers:
  value: 5
optimizer:
  value: adam
weightDecay:
  value: 0.0005
weightInit:
  value: random
