wandb_version: 1

activationFunc:
  value: sigmoid
batchSize:
  value: 16
hiddenLayer_Size:
  value: 64
learningRate:
  value: 0.0001
num_epochs:
  value: 5
num_hiddenLayers:
  value: 4
optimizer:
  value: rmsprop
weightDecay:
  value: 0.5
weightInit:
  value: random
