wandb_version: 1

activationFunc:
  value: tanh
batchSize:
  value: 32
hiddenLayer_Size:
  value: 128
learningRate:
  value: 0.001
num_epochs:
  value: 5
num_hiddenLayers:
  value: 4
optimizer:
  value: sgd
weightDecay:
  value: 0.5
weightInit:
  value: xavier
