wandb_version: 1

activationFunc:
  value: relu
batchSize:
  value: 64
hiddenLayer_Size:
  value: 128
learningRate:
  value: 0.0001
num_epochs:
  value: 5
num_hiddenLayers:
  value: 5
optimizer:
  value: momentum
weightDecay:
  value: 0.5
weightInit:
  value: xavier
