wandb_version: 1

activationFunc:
  value: tanh
batchSize:
  value: 16
hiddenLayer_Size:
  value: 64
learningRate:
  value: 0.001
num_epochs:
  value: 10
num_hiddenLayers:
  value: 5
optimizer:
  value: nadam
weightDecay:
  value: 0.5
weightInit:
  value: xavier
