wandb_version: 1

activationFunc:
  value: tanh
batchSize:
  value: 64
hiddenLayer_Size:
  value: 32
learningRate:
  value: 0.001
num_epochs:
  value: 10
num_hiddenLayers:
  value: 3
optimizer:
  value: sgd
weightDecay:
  value: 0
weightInit:
  value: random
