wandb_version: 1

activationFunc:
  value: sigmoid
batchSize:
  value: 64
hiddenLayer_Size:
  value: 128
learningRate:
  value: 0.0001
num_epochs:
  value: 10
num_hiddenLayers:
  value: 3
optimizer:
  value: nadam
weightDecay:
  value: 0.5
weightInit:
  value: random
