wandb_version: 1

activationFunc:
  value: tanh
batchSize:
  value: 64
hiddenLayer_Size:
  value: 128
learningRate:
  value: 0.001
num_epochs:
  value: 10
num_hiddenLayers:
  value: 4
optimizer:
  value: nadam
weightDecay:
  value: 0
weightInit:
  value: random
