wandb_version: 1

activationFunction:
  value: tanh
batchSize:
  value: 32
epochs:
  value: 10
hiddenLayerSize:
  value: 128
hiddenLayers:
  value: 4
learningRate:
  value: 0.001
optimizer:
  value: rmsprop
weightDecay:
  value: 0.0005
weightInitialisation:
  value: xavier
