wandb_version: 1

activationFunction:
  value: tanh
batchSize:
  value: 16
epochs:
  value: 5
hiddenLayerSize:
  value: 128
hiddenLayers:
  value: 4
learningRate:
  value: 0.001
optimizer:
  value: nadam
weightDecay:
  value: 0.0005
weightInitialisation:
  value: random
