wandb_version: 1

activationFunction:
  value: tanh
batchSize:
  value: 64
epochs:
  value: 10
hiddenLayerSize:
  value: 128
hiddenLayers:
  value: 3
learningRate:
  value: 0.001
optimizer:
  value: adam
weightDecay:
  value: 0.0005
weightInitialisation:
  value: xavier
