_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
                - 105
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
                - 105
            "3":
                - 2
                - 14
                - 23
                - 24
                - 55
            "4": 3.12.9
            "5": 0.19.8
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
activationFunc:
    value: tanh
batchSize:
    value: 132
hiddenLayer_Size:
    value: 64
learningRate:
    value: 0.0001
num_epochs:
    value: 10
num_hiddenLayers:
    value: 5
optimizer:
    value: momentum
weightDecay:
    value: 0
weightInit:
    value: xavier
