wandb_version: 1

activationFunc:
  value: tanh
batchSize:
  value: 132
hiddenLayer_Size:
  value: 64
learningRate:
  value: 0.0001
num_epochs:
  value: 10
num_hiddenLayers:
  value: 3
optimizer:
  value: nadam
weightDecay:
  value: 0.0005
weightInit:
  value: xavier
