wandb_version: 1

activationFunc:
  value: relu
batchSize:
  value: 116
hiddenLayer_Size:
  value: 32
learningRate:
  value: 0.0001
num_epochs:
  value: 20
num_hiddenLayers:
  value: 3
optimizer:
  value: sgd
weightDecay:
  value: 0.5
weightInit:
  value: random
