wandb_version: 1

activationFunc:
  value: relu
batchSize:
  value: 164
hiddenLayer_Size:
  value: 128
learningRate:
  value: 0.001
num_epochs:
  value: 20
num_hiddenLayers:
  value: 4
optimizer:
  value: sgd
weightDecay:
  value: 0.5
weightInit:
  value: xavier
