wandb_version: 1

activationFunc:
  value: tanh
batchSize:
  value: 132
hiddenLayer_Size:
  value: 64
learningRate:
  value: 0.001
num_epochs:
  value: 20
num_hiddenLayers:
  value: 5
optimizer:
  value: sgd
weightDecay:
  value: 0.0005
weightInit:
  value: random
