wandb_version: 1

activationFunc:
  value: sigmoid
batchSize:
  value: 164
hiddenLayer_Size:
  value: 128
learningRate:
  value: 0.001
num_epochs:
  value: 20
num_hiddenLayers:
  value: 5
optimizer:
  value: sgd
weightDecay:
  value: 0
weightInit:
  value: xavier
