wandb_version: 1

activationFunction:
  value: sigmoid
batchSize:
  value: 64
epochs:
  value: 5
hiddenLayerSize:
  value: 128
hiddenLayers:
  value: 4
learningRate:
  value: 0.0001
optimizer:
  value: momentum
weightDecay:
  value: 0
weightInitialisation:
  value: xavier
