wandb_version: 1

activationFunc:
  value: sigmoid
batchSize:
  value: 132
hiddenLayer_Size:
  value: 64
learningRate:
  value: 0.0001
num_epochs:
  value: 20
num_hiddenLayers:
  value: 4
optimizer:
  value: momentum
weightDecay:
  value: 0
weightInit:
  value: random
