wandb_version: 1

activationFunc:
  value: relu
batchSize:
  value: 164
hiddenLayer_Size:
  value: 32
learningRate:
  value: 0.001
num_epochs:
  value: 5
num_hiddenLayers:
  value: 5
optimizer:
  value: adam
weightDecay:
  value: 0.5
weightInit:
  value: random
