_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
                - 105
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
                - 105
            "3":
                - 2
                - 14
                - 17
                - 23
                - 24
                - 55
            "4": 3.12.9
            "5": 0.19.8
            "8":
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
activationFunction:
    value: relu
batchSize:
    value: 64
epochs:
    value: 5
hiddenLayerSize:
    value: 32
hiddenLayers:
    value: 3
learningRate:
    value: 0.001
optimizer:
    value: rmsprop
weightDecay:
    value: 0.5
weightInitialisation:
    value: xavier
