wandb_version: 1

activationFunc:
  value: tanh
batchSize:
  value: 132
hiddenLayer_Size:
  value: 64
learningRate:
  value: 0.0001
num_epochs:
  value: 5
num_hiddenLayers:
  value: 5
optimizer:
  value: nadam
weightDecay:
  value: 0.5
weightInit:
  value: xavier
