wandb_version: 1

activationFunc:
  value: tanh
batchSize:
  value: 116
hiddenLayer_Size:
  value: 32
learningRate:
  value: 0.0001
num_epochs:
  value: 10
num_hiddenLayers:
  value: 3
optimizer:
  value: adam
weightDecay:
  value: 0.0005
weightInit:
  value: random
