wandb_version: 1

activationFunction:
  value: relu
batchSize:
  value: 64
epochs:
  value: 5
hiddenLayerSize:
  value: 32
hiddenLayers:
  value: 3
learningRate:
  value: 0.001
optimizer:
  value: nesterov
weightDecay:
  value: 0
weightInitialisation:
  value: xavier
