wandb_version: 1

activationFunction:
  value: tanh
batchSize:
  value: 64
epochs:
  value: 10
hiddenLayerSize:
  value: 64
hiddenLayers:
  value: 5
learningRate:
  value: 0.001
optimizer:
  value: nesterov
weightDecay:
  value: 0.0005
weightInitialisation:
  value: xavier
