wandb_version: 1

activationFunc:
  value: sigmoid
batchSize:
  value: 32
hiddenLayer_Size:
  value: 64
learningRate:
  value: 0.001
num_epochs:
  value: 20
num_hiddenLayers:
  value: 5
optimizer:
  value: rmsprop
weightDecay:
  value: 0.5
weightInit:
  value: xavier
