wandb_version: 1

activationFunc:
  value: sigmoid
batchSize:
  value: 32
hiddenLayer_Size:
  value: 128
learningRate:
  value: 0.0001
num_epochs:
  value: 20
num_hiddenLayers:
  value: 3
optimizer:
  value: momentum
weightDecay:
  value: 0
weightInit:
  value: xavier
