wandb_version: 1

activationFunc:
  value: tanh
batchSize:
  value: 64
hiddenLayer_Size:
  value: 64
learningRate:
  value: 0.001
num_epochs:
  value: 10
num_hiddenLayers:
  value: 5
optimizer:
  value: rmsprop
weightDecay:
  value: 0.0005
weightInit:
  value: xavier
