wandb_version: 1

activationFunc:
  value: relu
batchSize:
  value: 16
hiddenLayer_Size:
  value: 32
learningRate:
  value: 0.0001
num_epochs:
  value: 10
num_hiddenLayers:
  value: 4
optimizer:
  value: rmsprop
weightDecay:
  value: 0.0005
weightInit:
  value: random
