wandb_version: 1

activationFunc:
  value: relu
batchSize:
  value: 16
hiddenLayer_Size:
  value: 128
learningRate:
  value: 0.001
num_epochs:
  value: 5
num_hiddenLayers:
  value: 5
optimizer:
  value: sgd
weightDecay:
  value: 0
weightInit:
  value: random
