wandb_version: 1

activationFunc:
  value: tanh
batchSize:
  value: 32
hiddenLayer_Size:
  value: 128
learningRate:
  value: 0.0001
num_epochs:
  value: 5
num_hiddenLayers:
  value: 3
optimizer:
  value: nadam
weightDecay:
  value: 0.0005
weightInit:
  value: xavier
