wandb_version: 1

activationFunc:
  value: tanh
batchSize:
  value: 16
hiddenLayer_Size:
  value: 128
learningRate:
  value: 0.001
num_epochs:
  value: 5
num_hiddenLayers:
  value: 3
optimizer:
  value: adam
weightDecay:
  value: 0.5
weightInit:
  value: xavier
