wandb_version: 1

activationFunc:
  value: tanh
batchSize:
  value: 32
hiddenLayer_Size:
  value: 32
learningRate:
  value: 0.001
num_epochs:
  value: 10
num_hiddenLayers:
  value: 4
optimizer:
  value: momentum
weightDecay:
  value: 0.0005
weightInit:
  value: random
