wandb_version: 1

activationFunc:
  value: sigmoid
batchSize:
  value: 16
hiddenLayer_Size:
  value: 64
learningRate:
  value: 0.001
num_epochs:
  value: 5
num_hiddenLayers:
  value: 5
optimizer:
  value: adam
weightDecay:
  value: 0.5
weightInit:
  value: xavier
