wandb_version: 1

activationFunc:
  value: sigmoid
batchSize:
  value: 32
hiddenLayer_Size:
  value: 32
learningRate:
  value: 0.001
num_epochs:
  value: 5
num_hiddenLayers:
  value: 3
optimizer:
  value: nesterov
weightDecay:
  value: 0
weightInit:
  value: xavier
