wandb_version: 1

activationFunc:
  value: relu
batchSize:
  value: 64
hiddenLayer_Size:
  value: 32
learningRate:
  value: 0.0001
num_epochs:
  value: 5
num_hiddenLayers:
  value: 3
optimizer:
  value: sgd
weightDecay:
  value: 0.0005
weightInit:
  value: random
