wandb_version: 1

activationFunction:
  value: tanh
batchSize:
  value: 32
epochs:
  value: 5
hiddenLayerSize:
  value: 64
hiddenLayers:
  value: 5
learningRate:
  value: 0.001
optimizer:
  value: sgd
weightDecay:
  value: 0.0005
weightInitialisation:
  value: xavier
