wandb_version: 1

activationFunction:
  value: sigmoid
batchSize:
  value: 16
epochs:
  value: 10
hiddenLayerSize:
  value: 64
hiddenLayers:
  value: 3
learningRate:
  value: 0.0001
optimizer:
  value: nadam
weightDecay:
  value: 0
weightInitialisation:
  value: random
