wandb_version: 1

activationFunction:
  value: tanh
batchSize:
  value: 16
epochs:
  value: 10
hiddenLayerSize:
  value: 32
hiddenLayers:
  value: 5
learningRate:
  value: 0.0001
optimizer:
  value: momentum
weightDecay:
  value: 0.0005
weightInitialisation:
  value: random
