wandb_version: 1

activationFunction:
  value: relu
batchSize:
  value: 32
epochs:
  value: 5
hiddenLayerSize:
  value: 128
hiddenLayers:
  value: 3
learningRate:
  value: 0.001
optimizer:
  value: nadam
weightDecay:
  value: 0
weightInitialisation:
  value: xavier
