wandb_version: 1

activationFunction:
  value: sigmoid
batchSize:
  value: 32
epochs:
  value: 10
hiddenLayerSize:
  value: 128
hiddenLayers:
  value: 5
learningRate:
  value: 0.0001
optimizer:
  value: rmsprop
weightDecay:
  value: 0.5
weightInitialisation:
  value: random
