wandb_version: 1

activationFunction:
  value: relu
batchSize:
  value: 16
epochs:
  value: 10
hiddenLayerSize:
  value: 64
hiddenLayers:
  value: 4
learningRate:
  value: 0.0001
optimizer:
  value: sgd
weightDecay:
  value: 0
weightInitialisation:
  value: xavier
