wandb_version: 1

activationFunction:
  value: relu
batchSize:
  value: 64
epochs:
  value: 10
hiddenLayerSize:
  value: 64
hiddenLayers:
  value: 5
learningRate:
  value: 0.0001
optimizer:
  value: rmsprop
weightDecay:
  value: 0.0005
weightInitialisation:
  value: random
