wandb_version: 1

activationFunction:
  value: relu
batchSize:
  value: 16
epochs:
  value: 5
hiddenLayerSize:
  value: 32
hiddenLayers:
  value: 4
learningRate:
  value: 0.001
optimizer:
  value: nadam
weightDecay:
  value: 0.5
weightInitialisation:
  value: random
