wandb_version: 1

activationFunc:
  value: sigmoid
batchSize:
  value: 116
hiddenLayer_Size:
  value: 64
learningRate:
  value: 0.0001
num_epochs:
  value: 5
num_hiddenLayers:
  value: 3
optimizer:
  value: adam
weightDecay:
  value: 0
weightInit:
  value: random
