wandb_version: 1

activationFunc:
  value: tanh
batchSize:
  value: 116
hiddenLayer_Size:
  value: 64
learningRate:
  value: 0.0001
num_epochs:
  value: 5
num_hiddenLayers:
  value: 4
optimizer:
  value: momentum
weightDecay:
  value: 0.0005
weightInit:
  value: xavier
